<?php

namespace Database\Seeders;

use App\Models\Nilai;
use Illuminate\Database\Seeder;

class NilaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Nilai::create([
            'calon_paskibraka_id' => 1,
            'akademik' => 90,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 90,
            'penghormatan' => 80,
            'belok' => 90,
            'hadap' => 88,
            'lari' => 8,
            'pushup' => 58,
            'situp' => 50,
            'pullup' => 8,
            'tb' => 176,
            'bb' => 70,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 2,
            'akademik' => 90,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 85,
            'penghormatan' => 80,
            'belok' => 90,
            'hadap' => 80,
            'lari' => 7,
            'pushup' => 42,
            'situp' => 49,
            'pullup' => 5,
            'tb' => 173,
            'bb' => 68,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 3,
            'akademik' => 88,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 87,
            'penghormatan' => 85,
            'belok' => 80,
            'hadap' => 80,
            'lari' => 7,
            'pushup' => 45,
            'situp' => 49,
            'pullup' => 6,
            'tb' => 172,
            'bb' => 63,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 4,
            'akademik' => 85,
            'jalan_ditempat' => 87,
            'langkah_tegap' => 90,
            'penghormatan' => 86,
            'belok' => 85,
            'hadap' => 83,
            'lari' => 6,
            'pushup' => 49,
            'situp' => 42,
            'pullup' => 6,
            'tb' => 171,
            'bb' => 63,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 5,
            'akademik' => 80,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 80,
            'penghormatan' => 80,
            'belok' => 85,
            'hadap' => 84,
            'lari' => 5,
            'pushup' => 49,
            'situp' => 45,
            'pullup' => 6,
            'tb' => 171,
            'bb' => 65,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 6,
            'akademik' => 87,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 90,
            'penghormatan' => 90,
            'belok' => 82,
            'hadap' => 80,
            'lari' => 6,
            'pushup' => 40,
            'situp' => 48,
            'pullup' => 6,
            'tb' => 170,
            'bb' => 70,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 7,
            'akademik' => 84,
            'jalan_ditempat' => 85,
            'langkah_tegap' => 80,
            'penghormatan' => 80,
            'belok' => 83,
            'hadap' => 87,
            'lari' => 6,
            'pushup' => 52,
            'situp' => 40,
            'pullup' => 4,
            'tb' => 170,
            'bb' => 65,
            'bentuk_kaki' => 3
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 8,
            'akademik' => 85,
            'jalan_ditempat' => 88,
            'langkah_tegap' => 85,
            'penghormatan' => 87,
            'belok' => 90,
            'hadap' => 88,
            'lari' => 6,
            'pushup' => 40,
            'situp' => 40,
            'pullup' => 7,
            'tb' => 170,
            'bb' => 65,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 9,
            'akademik' => 80,
            'jalan_ditempat' => 84,
            'langkah_tegap' => 80,
            'penghormatan' => 85,
            'belok' => 87,
            'hadap' => 86,
            'lari' => 7,
            'pushup' => 53,
            'situp' => 39,
            'pullup' => 7,
            'tb' => 170,
            'bb' => 68,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 10,
            'akademik' => 86,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 90,
            'penghormatan' => 80,
            'belok' => 86,
            'hadap' => 86,
            'lari' => 5,
            'pushup' => 47,
            'situp' => 44,
            'pullup' => 9,
            'tb' => 170,
            'bb' => 70,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 11,
            'akademik' => 90,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 83,
            'penghormatan' => 90,
            'belok' => 85,
            'hadap' => 80,
            'lari' => 6,
            'pushup' => 37,
            'situp' => 48,
            'pullup' => 9,
            'tb' => 170,
            'bb' => 68,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 12,
            'akademik' => 90,
            'jalan_ditempat' => 83,
            'langkah_tegap' => 80,
            'penghormatan' => 80,
            'belok' => 80,
            'hadap' => 85,
            'lari' => 7,
            'pushup' => 55,
            'situp' => 40,
            'pullup' => 6,
            'tb' => 170,
            'bb' => 58,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 13,
            'akademik' => 85,
            'jalan_ditempat' => 85,
            'langkah_tegap' => 87,
            'penghormatan' => 90,
            'belok' => 90,
            'hadap' => 80,
            'lari' => 5,
            'pushup' => 50,
            'situp' => 50,
            'pullup' => 6,
            'tb' => 169,
            'bb' => 61,
            'bentuk_kaki' => 3
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 14,
            'akademik' => 87,
            'jalan_ditempat' => 87,
            'langkah_tegap' => 88,
            'penghormatan' => 85,
            'belok' => 80,
            'hadap' => 83,
            'lari' => 6,
            'pushup' => 35,
            'situp' => 45,
            'pullup' => 11,
            'tb' => 169,
            'bb' => 55,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 15,
            'akademik' => 85,
            'jalan_ditempat' => 85,
            'langkah_tegap' => 80,
            'penghormatan' => 90,
            'belok' => 85,
            'hadap' => 80,
            'lari' => 6,
            'pushup' => 38,
            'situp' => 30,
            'pullup' => 60,
            'tb' => 168,
            'bb' => 62,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 16,
            'akademik' => 85,
            'jalan_ditempat' => 85,
            'langkah_tegap' => 80,
            'penghormatan' => 87,
            'belok' => 80,
            'hadap' => 85,
            'lari' => 6,
            'pushup' => 45,
            'situp' => 35,
            'pullup' => 7,
            'tb' => 168,
            'bb' => 57,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 17,
            'akademik' => 90,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 85,
            'penghormatan' => 90,
            'belok' => 80,
            'hadap' => 86,
            'lari' => 5,
            'pushup' => 50,
            'situp' => 34,
            'pullup' => 5,
            'tb' => 168,
            'bb' => 65,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 18,
            'akademik' => 90,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 85,
            'penghormatan' => 80,
            'belok' => 87,
            'hadap' => 85,
            'lari' => 5,
            'pushup' => 38,
            'situp' => 45,
            'pullup' => 5,
            'tb' => 168,
            'bb' => 62,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 19,
            'akademik' => 88,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 85,
            'penghormatan' => 85,
            'belok' => 90,
            'hadap' => 85,
            'lari' => 5,
            'pushup' => 40,
            'situp' => 45,
            'pullup' => 53,
            'tb' => 167,
            'bb' => 55,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 20,
            'akademik' => 85,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 83,
            'penghormatan' => 85,
            'belok' => 85,
            'hadap' => 80,
            'lari' => 7,
            'pushup' => 51,
            'situp' => 30,
            'pullup' => 6,
            'tb' => 167,
            'bb' => 60,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 21,
            'akademik' => 80,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 80,
            'penghormatan' => 80,
            'belok' => 86,
            'hadap' => 85,
            'lari' => 5,
            'pushup' => 40,
            'situp' => 42,
            'pullup' => 8,
            'tb' => 167,
            'bb' => 53,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 22,
            'akademik' => 87,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 90,
            'penghormatan' => 82,
            'belok' => 90,
            'hadap' => 86,
            'lari' => 6,
            'pushup' => 54,
            'situp' => 50,
            'pullup' => 7,
            'tb' => 167,
            'bb' => 55,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 23,
            'akademik' => 84,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 85,
            'penghormatan' => 80,
            'belok' => 90,
            'hadap' => 80,
            'lari' => 4,
            'pushup' => 38,
            'situp' => 45,
            'pullup' => 50,
            'tb' => 167,
            'bb' => 60,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 24,
            'akademik' => 85,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 87,
            'penghormatan' => 85,
            'belok' => 90,
            'hadap' => 86,
            'lari' => 6,
            'pushup' => 42,
            'situp' => 45,
            'pullup' => 54,
            'tb' => 166,
            'bb' => 65,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 25,
            'akademik' => 80,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 83,
            'penghormatan' => 90,
            'belok' => 80,
            'hadap' => 80,
            'lari' => 7,
            'pushup' => 42,
            'situp' => 53,
            'pullup' => 47,
            'tb' => 165,
            'bb' => 62,
            'bentuk_kaki' => 3
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 26,
            'akademik' => 86,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 82,
            'penghormatan' => 85,
            'belok' => 86,
            'hadap' => 80,
            'lari' => 6,
            'pushup' => 36,
            'situp' => 35,
            'pullup' => 53,
            'tb' => 165,
            'bb' => 52,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 27,
            'akademik' => 90,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 84,
            'penghormatan' => 80,
            'belok' => 85,
            'hadap' => 80,
            'lari' => 6,
            'pushup' => 40,
            'situp' => 38,
            'pullup' => 12,
            'tb' => 163,
            'bb' => 60,
            'bentuk_kaki' => 3
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 28,
            'akademik' => 90,
            'jalan_ditempat' => 83,
            'langkah_tegap' => 85,
            'penghormatan' => 85,
            'belok' => 80,
            'hadap' => 85,
            'lari' => 5,
            'pushup' => 40,
            'situp' => 45,
            'pullup' => 40,
            'tb' => 163,
            'bb' => 64,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 29,
            'akademik' => 85,
            'jalan_ditempat' => 86,
            'langkah_tegap' => 90,
            'penghormatan' => 85,
            'belok' => 84,
            'hadap' => 80,
            'lari' => 6,
            'pushup' => 43,
            'situp' => 40,
            'pullup' => 43,
            'tb' => 160,
            'bb' => 65,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 30,
            'akademik' => 87,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 90,
            'penghormatan' => 87,
            'belok' => 86,
            'hadap' => 80,
            'lari' => 6,
            'pushup' => 40,
            'situp' => 40,
            'pullup' => 63,
            'tb' => 158,
            'bb' => 60,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 31,
            'akademik' => 85,
            'jalan_ditempat' => 85,
            'langkah_tegap' => 85,
            'penghormatan' => 80,
            'belok' => 83,
            'hadap' => 85,
            'lari' => 4,
            'pushup' => 30,
            'situp' => 35,
            'pullup' => 45,
            'tb' => 158,
            'bb' => 60,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 32,
            'akademik' => 85,
            'jalan_ditempat' => 87,
            'langkah_tegap' => 80,
            'penghormatan' => 80,
            'belok' => 85,
            'hadap' => 88,
            'lari' => 5,
            'pushup' => 34,
            'situp' => 30,
            'pullup' => 48,
            'tb' => 157,
            'bb' => 50,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 33,
            'akademik' => 84,
            'jalan_ditempat' => 78,
            'langkah_tegap' => 75,
            'penghormatan' => 77,
            'belok' => 70,
            'hadap' => 75,
            'lari' => 4,
            'pushup' => 30,
            'situp' => 34,
            'pullup' => 4,
            'tb' => 168,
            'bb' => 55,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 34,
            'akademik' => 85,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 82,
            'penghormatan' => 80,
            'belok' => 80,
            'hadap' => 80,
            'lari' => 5,
            'pushup' => 34,
            'situp' => 28,
            'pullup' => 32,
            'tb' => 166,
            'bb' => 50,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 35,
            'akademik' => 80,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 80,
            'penghormatan' => 80,
            'belok' => 80,
            'hadap' => 80,
            'lari' => 4,
            'pushup' => 32,
            'situp' => 30,
            'pullup' => 4,
            'tb' => 165,
            'bb' => 60,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 36,
            'akademik' => 86,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 78,
            'penghormatan' => 80,
            'belok' => 80,
            'hadap' => 80,
            'lari' => 5,
            'pushup' => 33,
            'situp' => 30,
            'pullup' => 5,
            'tb' => 165,
            'bb' => 58,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 37,
            'akademik' => 90,
            'jalan_ditempat' => 75,
            'langkah_tegap' => 70,
            'penghormatan' => 80,
            'belok' => 80,
            'hadap' => 78,
            'lari' => 4,
            'pushup' => 20,
            'situp' => 12,
            'pullup' => 33,
            'tb' => 165,
            'bb' => 60,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 38,
            'akademik' => 90,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 82,
            'penghormatan' => 85,
            'belok' => 80,
            'hadap' => 80,
            'lari' => 4,
            'pushup' => 35,
            'situp' => 30,
            'pullup' => 35,
            'tb' => 162,
            'bb' => 60,
            'bentuk_kaki' => 1
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 39,
            'akademik' => 85,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 82,
            'penghormatan' => 82,
            'belok' => 80,
            'hadap' => 78,
            'lari' => 5,
            'pushup' => 40,
            'situp' => 35,
            'pullup' => 2,
            'tb' => 160,
            'bb' => 62,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 40,
            'akademik' => 87,
            'jalan_ditempat' => 78,
            'langkah_tegap' => 80,
            'penghormatan' => 85,
            'belok' => 80,
            'hadap' => 80,
            'lari' => 3,
            'pushup' => 23,
            'situp' => 20,
            'pullup' => 35,
            'tb' => 160,
            'bb' => 49,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 41,
            'akademik' => 85,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 80,
            'penghormatan' => 80,
            'belok' => 80,
            'hadap' => 78,
            'lari' => 3,
            'pushup' => 28,
            'situp' => 20,
            'pullup' => 38,
            'tb' => 157,
            'bb' => 62,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 42,
            'akademik' => 85,
            'jalan_ditempat' => 82,
            'langkah_tegap' => 80,
            'penghormatan' => 85,
            'belok' => 80,
            'hadap' => 80,
            'lari' => 5,
            'pushup' => 32,
            'situp' => 29,
            'pullup' => 40,
            'tb' => 153,
            'bb' => 50,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 43,
            'akademik' => 85,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 85,
            'penghormatan' => 90,
            'belok' => 80,
            'hadap' => 90,
            'lari' => 7,
            'pushup' => 56,
            'situp' => 54,
            'pullup' => 7,
            'tb' => 176,
            'bb' => 76,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 44,
            'akademik' => 90,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 80,
            'penghormatan' => 80,
            'belok' => 80,
            'hadap' => 80,
            'lari' => 6,
            'pushup' => 50,
            'situp' => 35,
            'pullup' => 6,
            'tb' => 175,
            'bb' => 67,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 45,
            'akademik' => 88,
            'jalan_ditempat' => 87,
            'langkah_tegap' => 85,
            'penghormatan' => 90,
            'belok' => 80,
            'hadap' => 85,
            'lari' => 6,
            'pushup' => 43,
            'situp' => 45,
            'pullup' => 11,
            'tb' => 174,
            'bb' => 62,
            'bentuk_kaki' => 3
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 46,
            'akademik' => 85,
            'jalan_ditempat' => 86,
            'langkah_tegap' => 80,
            'penghormatan' => 80,
            'belok' => 80,
            'hadap' => 85,
            'lari' => 6,
            'pushup' => 43,
            'situp' => 48,
            'pullup' => 5,
            'tb' => 173,
            'bb' => 67,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 47,
            'akademik' => 80,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 83,
            'penghormatan' => 85,
            'belok' => 87,
            'hadap' => 80,
            'lari' => 7,
            'pushup' => 52,
            'situp' => 30,
            'pullup' => 9,
            'tb' => 172,
            'bb' => 72,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 48,
            'akademik' => 87,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 84,
            'penghormatan' => 90,
            'belok' => 85,
            'hadap' => 87,
            'lari' => 6,
            'pushup' => 53,
            'situp' => 40,
            'pullup' => 11,
            'tb' => 172,
            'bb' => 61,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 49,
            'akademik' => 84,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 85,
            'penghormatan' => 85,
            'belok' => 80,
            'hadap' => 80,
            'lari' => 5,
            'pushup' => 35,
            'situp' => 45,
            'pullup' => 43,
            'tb' => 172,
            'bb' => 67,
            'bentuk_kaki' => 3
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 50,
            'akademik' => 85,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 90,
            'penghormatan' => 90,
            'belok' => 82,
            'hadap' => 90,
            'lari' => 6,
            'pushup' => 55,
            'situp' => 47,
            'pullup' => 10,
            'tb' => 171,
            'bb' => 58,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 51,
            'akademik' => 80,
            'jalan_ditempat' => 85,
            'langkah_tegap' => 80,
            'penghormatan' => 83,
            'belok' => 80,
            'hadap' => 80,
            'lari' => 6,
            'pushup' => 50,
            'situp' => 49,
            'pullup' => 11,
            'tb' => 170,
            'bb' => 65,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 52,
            'akademik' => 86,
            'jalan_ditempat' => 85,
            'langkah_tegap' => 85,
            'penghormatan' => 85,
            'belok' => 85,
            'hadap' => 85,
            'lari' => 6,
            'pushup' => 45,
            'situp' => 45,
            'pullup' => 12,
            'tb' => 170,
            'bb' => 54,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 53,
            'akademik' => 90,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 86,
            'penghormatan' => 86,
            'belok' => 85,
            'hadap' => 90,
            'lari' => 6,
            'pushup' => 50,
            'situp' => 50,
            'pullup' => 10,
            'tb' => 170,
            'bb' => 70,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 54,
            'akademik' => 90,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 80,
            'penghormatan' => 90,
            'belok' => 87,
            'hadap' => 90,
            'lari' => 6,
            'pushup' => 43,
            'situp' => 43,
            'pullup' => 6,
            'tb' => 168,
            'bb' => 58,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 55,
            'akademik' => 85,
            'jalan_ditempat' => 86,
            'langkah_tegap' => 90,
            'penghormatan' => 87,
            'belok' => 86,
            'hadap' => 90,
            'lari' => 8,
            'pushup' => 55,
            'situp' => 50,
            'pullup' => 13,
            'tb' => 168,
            'bb' => 65,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 56,
            'akademik' => 87,
            'jalan_ditempat' => 86,
            'langkah_tegap' => 90,
            'penghormatan' => 80,
            'belok' => 80,
            'hadap' => 84,
            'lari' => 5,
            'pushup' => 45,
            'situp' => 48,
            'pullup' => 55,
            'tb' => 168,
            'bb' => 56,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 57,
            'akademik' => 85,
            'jalan_ditempat' => 85,
            'langkah_tegap' => 83,
            'penghormatan' => 90,
            'belok' => 85,
            'hadap' => 87,
            'lari' => 6,
            'pushup' => 47,
            'situp' => 45,
            'pullup' => 7,
            'tb' => 168,
            'bb' => 62,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 58,
            'akademik' => 85,
            'jalan_ditempat' => 86,
            'langkah_tegap' => 80,
            'penghormatan' => 87,
            'belok' => 90,
            'hadap' => 80,
            'lari' => 6,
            'pushup' => 40,
            'situp' => 45,
            'pullup' => 5,
            'tb' => 167,
            'bb' => 60,
            'bentuk_kaki' => 3
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 59,
            'akademik' => 90,
            'jalan_ditempat' => 87,
            'langkah_tegap' => 90,
            'penghormatan' => 87,
            'belok' => 85,
            'hadap' => 85,
            'lari' => 6,
            'pushup' => 46,
            'situp' => 36,
            'pullup' => 5,
            'tb' => 167,
            'bb' => 65,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 60,
            'akademik' => 90,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 87,
            'penghormatan' => 90,
            'belok' => 85,
            'hadap' => 85,
            'lari' => 6,
            'pushup' => 50,
            'situp' => 50,
            'pullup' => 10,
            'tb' => 166,
            'bb' => 65,
            'bentuk_kaki' => 3
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 61,
            'akademik' => 88,
            'jalan_ditempat' => 85,
            'langkah_tegap' => 80,
            'penghormatan' => 85,
            'belok' => 90,
            'hadap' => 80,
            'lari' => 6,
            'pushup' => 43,
            'situp' => 39,
            'pullup' => 6,
            'tb' => 166,
            'bb' => 60,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 62,
            'akademik' => 85,
            'jalan_ditempat' => 87,
            'langkah_tegap' => 80,
            'penghormatan' => 80,
            'belok' => 85,
            'hadap' => 83,
            'lari' => 6,
            'pushup' => 48,
            'situp' => 45,
            'pullup' => 6,
            'tb' => 166,
            'bb' => 56,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 63,
            'akademik' => 80,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 85,
            'penghormatan' => 83,
            'belok' => 90,
            'hadap' => 85,
            'lari' => 8,
            'pushup' => 53,
            'situp' => 50,
            'pullup' => 11,
            'tb' => 165,
            'bb' => 66,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 64,
            'akademik' => 87,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 84,
            'penghormatan' => 80,
            'belok' => 80,
            'hadap' => 80,
            'lari' => 6,
            'pushup' => 52,
            'situp' => 40,
            'pullup' => 5,
            'tb' => 165,
            'bb' => 50,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 65,
            'akademik' => 84,
            'jalan_ditempat' => 85,
            'langkah_tegap' => 86,
            'penghormatan' => 80,
            'belok' => 90,
            'hadap' => 85,
            'lari' => 4,
            'pushup' => 35,
            'situp' => 45,
            'pullup' => 43,
            'tb' => 164,
            'bb' => 52,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 66,
            'akademik' => 85,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 80,
            'penghormatan' => 80,
            'belok' => 85,
            'hadap' => 80,
            'lari' => 6,
            'pushup' => 55,
            'situp' => 42,
            'pullup' => 9,
            'tb' => 164,
            'bb' => 60,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 67,
            'akademik' => 80,
            'jalan_ditempat' => 85,
            'langkah_tegap' => 83,
            'penghormatan' => 90,
            'belok' => 85,
            'hadap' => 88,
            'lari' => 7,
            'pushup' => 43,
            'situp' => 34,
            'pullup' => 10,
            'tb' => 164,
            'bb' => 59,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 68,
            'akademik' => 86,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 84,
            'penghormatan' => 80,
            'belok' => 80,
            'hadap' => 84,
            'lari' => 5,
            'pushup' => 38,
            'situp' => 49,
            'pullup' => 58,
            'tb' => 163,
            'bb' => 58,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 69,
            'akademik' => 90,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 80,
            'penghormatan' => 85,
            'belok' => 87,
            'hadap' => 80,
            'lari' => 7,
            'pushup' => 52,
            'situp' => 50,
            'pullup' => 7,
            'tb' => 162,
            'bb' => 50,
            'bentuk_kaki' => 3
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 70,
            'akademik' => 85,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 90,
            'penghormatan' => 80,
            'belok' => 80,
            'hadap' => 90,
            'lari' => 6,
            'pushup' => 40,
            'situp' => 35,
            'pullup' => 40,
            'tb' => 162,
            'bb' => 57,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 71,
            'akademik' => 80,
            'jalan_ditempat' => 85,
            'langkah_tegap' => 90,
            'penghormatan' => 80,
            'belok' => 90,
            'hadap' => 90,
            'lari' => 5,
            'pushup' => 38,
            'situp' => 42,
            'pullup' => 52,
            'tb' => 160,
            'bb' => 55,
            'bentuk_kaki' => 3
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 72,
            'akademik' => 87,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 85,
            'penghormatan' => 85,
            'belok' => 80,
            'hadap' => 85,
            'lari' => 6,
            'pushup' => 39,
            'situp' => 35,
            'pullup' => 54,
            'tb' => 160,
            'bb' => 50,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 73,
            'akademik' => 85,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 85,
            'penghormatan' => 90,
            'belok' => 80,
            'hadap' => 85,
            'lari' => 5,
            'pushup' => 48,
            'situp' => 53,
            'pullup' => 54,
            'tb' => 160,
            'bb' => 53,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 74,
            'akademik' => 90,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 90,
            'penghormatan' => 84,
            'belok' => 85,
            'hadap' => 80,
            'lari' => 5,
            'pushup' => 40,
            'situp' => 39,
            'pullup' => 50,
            'tb' => 160,
            'bb' => 50,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 75,
            'akademik' => 80,
            'jalan_ditempat' => 90,
            'langkah_tegap' => 85,
            'penghormatan' => 90,
            'belok' => 90,
            'hadap' => 83,
            'lari' => 5,
            'pushup' => 49,
            'situp' => 44,
            'pullup' => 47,
            'tb' => 159,
            'bb' => 54,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 76,
            'akademik' => 87,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 83,
            'penghormatan' => 88,
            'belok' => 87,
            'hadap' => 85,
            'lari' => 5,
            'pushup' => 45,
            'situp' => 46,
            'pullup' => 46,
            'tb' => 159,
            'bb' => 47,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 77,
            'akademik' => 84,
            'jalan_ditempat' => 86,
            'langkah_tegap' => 85,
            'penghormatan' => 80,
            'belok' => 90,
            'hadap' => 83,
            'lari' => 5,
            'pushup' => 35,
            'situp' => 30,
            'pullup' => 43,
            'tb' => 158,
            'bb' => 49,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 78,
            'akademik' => 80,
            'jalan_ditempat' => 70,
            'langkah_tegap' => 73,
            'penghormatan' => 80,
            'belok' => 77,
            'hadap' => 75,
            'lari' => 6,
            'pushup' => 29,
            'situp' => 35,
            'pullup' => 4,
            'tb' => 181,
            'bb' => 67,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 79,
            'akademik' => 87,
            'jalan_ditempat' => 75,
            'langkah_tegap' => 72,
            'penghormatan' => 84,
            'belok' => 70,
            'hadap' => 75,
            'lari' => 5,
            'pushup' => 40,
            'situp' => 40,
            'pullup' => 1,
            'tb' => 169,
            'bb' => 60,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 80,
            'akademik' => 84,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 82,
            'penghormatan' => 80,
            'belok' => 83,
            'hadap' => 80,
            'lari' => 3,
            'pushup' => 22,
            'situp' => 7,
            'pullup' => 37,
            'tb' => 165,
            'bb' => 45,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 81,
            'akademik' => 85,
            'jalan_ditempat' => 80,
            'langkah_tegap' => 70,
            'penghormatan' => 81,
            'belok' => 75,
            'hadap' => 72,
            'lari' => 4,
            'pushup' => 35,
            'situp' => 30,
            'pullup' => 2,
            'tb' => 164,
            'bb' => 47,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 82,
            'akademik' => 80,
            'jalan_ditempat' => 60,
            'langkah_tegap' => 66,
            'penghormatan' => 76,
            'belok' => 68,
            'hadap' => 70,
            'lari' => 3,
            'pushup' => 30,
            'situp' => 32,
            'pullup' => 3,
            'tb' => 163,
            'bb' => 53,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 83,
            'akademik' => 86,
            'jalan_ditempat' => 75,
            'langkah_tegap' => 70,
            'penghormatan' => 80,
            'belok' => 70,
            'hadap' => 72,
            'lari' => 4,
            'pushup' => 30,
            'situp' => 20,
            'pullup' => 1,
            'tb' => 162,
            'bb' => 54,
            'bentuk_kaki' => 5
        ]);
        Nilai::create([
            'calon_paskibraka_id' => 84,
            'akademik' => 90,
            'jalan_ditempat' => 83,
            'langkah_tegap' => 80,
            'penghormatan' => 82,
            'belok' => 73,
            'hadap' => 70,
            'lari' => 3,
            'pushup' => 10,
            'situp' => 12,
            'pullup' => 40,
            'tb' => 155,
            'bb' => 58,
            'bentuk_kaki' => 5
        ]);
    }
}
